URLShorter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
]

main/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from main import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('<str:shorted_url>', views.redirect_from_shorted_url, name='redirect_from_shorted_url'),
    path('add_url/', views.add_shorted_url, name='add_url'),
    path('remove_url/<int:id>', views.remove_shorted_link, name='remove_url'),
]

main/models.py
from django.db import models

class ShortedURL(models.Model):
    name = models.CharField(max_length=120, verbose_name="Назва")
    url = models.URLField(verbose_name="Посилання")
    shorted_url = models.URLField(verbose_name="Коротке посилання")
    clicks = models.IntegerField(default=0, verbose_name="Переходи")
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Коротке посилання'
        verbose_name_plural = 'Короткі посилання'

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class AddURLForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Назва')
    url = forms.URLField(widget=forms.TextInput(attrs={'class':'form-control'}), label='Посилання')

main/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import AddURLForm
from .models import  ShortedURL
import secrets


def create_shorted_url():
    return secrets.token_urlsafe(6)


@login_required(login_url='main:login')
def index(request):
    count = int(request.GET.get('count', 10))
    urls = ShortedURL.objects.all().order_by('-id')
    paginator = Paginator(urls, count)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    add_form = AddURLForm()
    return render(request, 'index.html', {
                                                            'urls': page_obj.object_list,
                                                            'page_obj': page_obj,
                                                            'page_count': paginator.num_pages,
                                                            'add_form': add_form,
    })


def remove_shorted_link(request, id):
    if not id:
        return redirect('main:index')
    ShortedURL.objects.get(id=id).delete()
    return redirect('main:index')


def add_shorted_url(request):
    if request.method == 'POST':
        form = AddURLForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            url = form.cleaned_data['url']
            shorted_url = ShortedURL(name=name, url=url, shorted_url=f'{request.build_absolute_uri(location="/")}{create_shorted_url()}')
            shorted_url.save()
            return redirect('main:index')

def redirect_from_shorted_url(request, shorted_url):
    try:
        url = ShortedURL.objects.get(shorted_url=f'{request.build_absolute_uri(location="/")}{shorted_url}')
        url.clicks += 1
        url.save()
        return redirect(url.url)
    except ShortedURL.DoesNotExist:
        return redirect('https://polymerservice.ua/')

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Сервіс коротких посилань{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://kit.fontawesome.com/ac57759988.js" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'header.html' %}
    <main>
        {% block content %}
        <!-- Контент страницы -->
        {% endblock %}
    </main>
    {% include 'footer.html' %}
</body>
</html>

main/templates/footer.html
<footer>
    <p style="display: block;
            width: 300px;
            margin: auto;">&copy; 2024 Polymerservice. Всі права захищено.</p>
</footer>

main/templates/header.html
<header>
    <h1>Сервіс коротких посилань polymerservice.ua</h1>
</header>

main/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="add-form">
        <form method="post" id="add-url-form" action="{% url 'main:add_url' %}">
            {% csrf_token %}
            {{ add_form.as_p }}
            <button type="submit">Створити посилання</button>
        </form>
    </div>
<table>
    <thead>
    <tr>
        <td>Назва</td>
        <td>Посилання</td>
        <td>Коротке посилання</td>
        <td>Переходи</td>
        <td>Видалити</td>
    </tr>
    </thead>
    <tbody>
        {% for url in urls %}
        	<tr>
                <td>{{ url.name }}</td>
                <td><a href="{{ url.url }}">{{ url.url }}</a></td>
                <td><a href="{{ url.shorted_url }}">{{ url.shorted_url }}</a></td>
                <td>{{ url.clicks }}</td>
                <td><a href="{% url "main:remove_url" id=url.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
            </tr>
        {% endfor %}

    </tbody>
</table>
    {% if page_count > 1 %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="previous"><a href="?page=1">&laquo; Перша</a></li>
                <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">Попередня</a></li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="active"><a href="?page={{ num }}">{{ num }}</a></li>
                {% else %}
                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="next"><a href="?page={{ page_obj.next_page_number }}">Наступна</a></li>
                <li class="next"><a href="?page={{ page_obj.paginator.num_pages }}">Остання &raquo;</a></li>

            {% endif %}
        </ul>
    {% endif %}

{% endblock %}